#!/usr/bin/env python3
"""
FastAPI CRUD Router Generator

Generates FastAPI CRUD routers from SQLModel/Pydantic models with proper
dependency injection, status codes, and error handling.
"""

import argparse
import ast
import re
import sys
from typing import List, Dict, Any


def parse_model_definition(model_code: str) -> Dict[str, Any]:
    """Parse SQLModel/Pydantic model definition to extract metadata."""
    try:
        tree = ast.parse(model_code)
    except SyntaxError as e:
        raise ValueError(f"Invalid Python code: {e}")

    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef):
            model_name = node.name
            fields = []
            bases = [base.id if isinstance(base, ast.Name) else str(base) for base in node.bases]

            # Extract fields from class body
            for item in node.body:
                if isinstance(item, ast.AnnAssign) and isinstance(item.target, ast.Name):
                    field_name = item.target.id
                    field_type = ast.unparse(item.annotation)

                    # Check if field is optional
                    is_optional = 'Optional' in field_type or '| None' in field_type or 'None |' in field_type
                    has_default = item.value is not None

                    fields.append({
                        'name': field_name,
                        'type': field_type,
                        'optional': is_optional or has_default
                    })

            return {
                'name': model_name,
                'fields': fields,
                'bases': bases,
                'table_name': model_name.lower() + 's'
            }

    raise ValueError("No class definition found in model code")


def generate_direct_pattern(model_info: Dict[str, Any], session_style: str) -> str:
    """Generate CRUD router with direct database operations."""
    model_name = model_info['name']
    table_name = model_info['table_name']
    fields = model_info['fields']

    # Determine session dependency
    if session_style == "generate":
        session_dep = """
# Database dependency (customize for your database setup)
def get_session():
    \"\"\"Database session dependency - implement your DB connection logic here.\"\"\"
    # Example for SQLModel:
    # engine = create_engine("sqlite:///database.db")
    # with Session(engine) as session:
    #     yield session
    raise NotImplementedError("Configure your database session")
"""
        session_param = "session = Depends(get_session)"
    else:
        session_dep = ""
        session_param = "session = Depends(get_db)"

    # Generate field list for create/update models
    field_defs = []
    for field in fields:
        if field['name'] not in ['id', 'created_at', 'updated_at']:
            field_defs.append(f"    {field['name']}: {field['type']}")

    create_fields = "\n".join(field_defs)

    code = f'''"""
FastAPI CRUD Router for {model_name}
Generated by fastapi_crud_builder skill
"""

from fastapi import APIRouter, Depends, HTTPException, status
from sqlmodel import Session, select
from typing import List
from .models import {model_name}  # Adjust import based on your project structure

router = APIRouter(prefix="/{table_name}", tags=["{table_name}"])
{session_dep}

# Pydantic models for request/response
class {model_name}Create(BaseModel):
{create_fields}

class {model_name}Update(BaseModel):
{create_fields}


@router.post("/", response_model={model_name}, status_code=status.HTTP_201_CREATED)
async def create_{model_name.lower()}(
    {model_name.lower()}_data: {model_name}Create,
    {session_param}
):
    """Create a new {model_name}."""
    try:
        {model_name.lower()} = {model_name}(**{model_name.lower()}_data.model_dump())
        session.add({model_name.lower()})
        session.commit()
        session.refresh({model_name.lower()})
        return {model_name.lower()}
    except Exception as e:
        session.rollback()
        # Handle unique constraint violations
        if "unique" in str(e).lower() or "duplicate" in str(e).lower():
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail=f"{model_name} already exists"
            )
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(e)
        )


@router.get("/", response_model=List[{model_name}])
async def list_{table_name}(
    skip: int = 0,
    limit: int = 100,
    {session_param}
):
    """List all {table_name} with pagination."""
    statement = select({model_name}).offset(skip).limit(limit)
    {table_name} = session.exec(statement).all()
    return {table_name}


@router.get("/{{item_id}}", response_model={model_name})
async def get_{model_name.lower()}(
    item_id: int,
    {session_param}
):
    """Get a specific {model_name} by ID."""
    {model_name.lower()} = session.get({model_name}, item_id)
    if not {model_name.lower()}:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"{model_name} not found"
        )
    return {model_name.lower()}


@router.put("/{{item_id}}", response_model={model_name})
async def update_{model_name.lower()}(
    item_id: int,
    {model_name.lower()}_data: {model_name}Update,
    {session_param}
):
    """Update an existing {model_name}."""
    {model_name.lower()} = session.get({model_name}, item_id)
    if not {model_name.lower()}:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"{model_name} not found"
        )

    try:
        # Update fields
        for key, value in {model_name.lower()}_data.model_dump(exclude_unset=True).items():
            setattr({model_name.lower()}, key, value)

        session.add({model_name.lower()})
        session.commit()
        session.refresh({model_name.lower()})
        return {model_name.lower()}
    except Exception as e:
        session.rollback()
        if "unique" in str(e).lower() or "duplicate" in str(e).lower():
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail=f"{model_name} already exists"
            )
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(e)
        )


@router.delete("/{{item_id}}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_{model_name.lower()}(
    item_id: int,
    {session_param}
):
    """Delete a {model_name}."""
    {model_name.lower()} = session.get({model_name}, item_id)
    if not {model_name.lower()}:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"{model_name} not found"
        )

    try:
        session.delete({model_name.lower()})
        session.commit()
    except Exception as e:
        session.rollback()
        # Handle foreign key constraints
        if "foreign key" in str(e).lower() or "constraint" in str(e).lower():
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail=f"Cannot delete {model_name}: referenced by other records"
            )
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(e)
        )
'''
    return code


def generate_repository_pattern(model_info: Dict[str, Any], session_style: str) -> str:
    """Generate CRUD router with repository pattern."""
    model_name = model_info['name']
    table_name = model_info['table_name']
    fields = model_info['fields']

    # Determine session dependency
    if session_style == "generate":
        session_dep = """
# Database dependency (customize for your database setup)
def get_session():
    \"\"\"Database session dependency - implement your DB connection logic here.\"\"\"
    # Example for SQLModel:
    # engine = create_engine("sqlite:///database.db")
    # with Session(engine) as session:
    #     yield session
    raise NotImplementedError("Configure your database session")
"""
        session_param = "session = Depends(get_session)"
    else:
        session_dep = ""
        session_param = "session = Depends(get_db)"

    # Generate field list for create/update models
    field_defs = []
    for field in fields:
        if field['name'] not in ['id', 'created_at', 'updated_at']:
            field_defs.append(f"    {field['name']}: {field['type']}")

    create_fields = "\n".join(field_defs)

    code = f'''"""
FastAPI CRUD Router for {model_name} with Repository Pattern
Generated by fastapi_crud_builder skill
"""

from fastapi import APIRouter, Depends, HTTPException, status
from sqlmodel import Session, select
from typing import List, Optional
from .models import {model_name}  # Adjust import based on your project structure

router = APIRouter(prefix="/{table_name}", tags=["{table_name}"])
{session_dep}

# Pydantic models for request/response
class {model_name}Create(BaseModel):
{create_fields}

class {model_name}Update(BaseModel):
{create_fields}


# Repository layer
class {model_name}Repository:
    """Repository for {model_name} database operations."""

    def __init__(self, session: Session):
        self.session = session

    def create(self, {model_name.lower()}_data: {model_name}Create) -> {model_name}:
        """Create a new {model_name}."""
        {model_name.lower()} = {model_name}(**{model_name.lower()}_data.model_dump())
        self.session.add({model_name.lower()})
        self.session.commit()
        self.session.refresh({model_name.lower()})
        return {model_name.lower()}

    def get_by_id(self, item_id: int) -> Optional[{model_name}]:
        """Get {model_name} by ID."""
        return self.session.get({model_name}, item_id)

    def get_all(self, skip: int = 0, limit: int = 100) -> List[{model_name}]:
        """Get all {table_name} with pagination."""
        statement = select({model_name}).offset(skip).limit(limit)
        return list(self.session.exec(statement).all())

    def update(self, item_id: int, {model_name.lower()}_data: {model_name}Update) -> Optional[{model_name}]:
        """Update an existing {model_name}."""
        {model_name.lower()} = self.session.get({model_name}, item_id)
        if not {model_name.lower()}:
            return None

        for key, value in {model_name.lower()}_data.model_dump(exclude_unset=True).items():
            setattr({model_name.lower()}, key, value)

        self.session.add({model_name.lower()})
        self.session.commit()
        self.session.refresh({model_name.lower()})
        return {model_name.lower()}

    def delete(self, item_id: int) -> bool:
        """Delete a {model_name}."""
        {model_name.lower()} = self.session.get({model_name}, item_id)
        if not {model_name.lower()}:
            return False

        self.session.delete({model_name.lower()})
        self.session.commit()
        return True


# Dependency for repository
def get_{model_name.lower()}_repository({session_param}) -> {model_name}Repository:
    """Get {model_name} repository instance."""
    return {model_name}Repository(session)


# Routes
@router.post("/", response_model={model_name}, status_code=status.HTTP_201_CREATED)
async def create_{model_name.lower()}(
    {model_name.lower()}_data: {model_name}Create,
    repository: {model_name}Repository = Depends(get_{model_name.lower()}_repository)
):
    """Create a new {model_name}."""
    try:
        return repository.create({model_name.lower()}_data)
    except Exception as e:
        if "unique" in str(e).lower() or "duplicate" in str(e).lower():
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail=f"{model_name} already exists"
            )
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(e)
        )


@router.get("/", response_model=List[{model_name}])
async def list_{table_name}(
    skip: int = 0,
    limit: int = 100,
    repository: {model_name}Repository = Depends(get_{model_name.lower()}_repository)
):
    """List all {table_name} with pagination."""
    return repository.get_all(skip=skip, limit=limit)


@router.get("/{{item_id}}", response_model={model_name})
async def get_{model_name.lower()}(
    item_id: int,
    repository: {model_name}Repository = Depends(get_{model_name.lower()}_repository)
):
    """Get a specific {model_name} by ID."""
    {model_name.lower()} = repository.get_by_id(item_id)
    if not {model_name.lower()}:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"{model_name} not found"
        )
    return {model_name.lower()}


@router.put("/{{item_id}}", response_model={model_name})
async def update_{model_name.lower()}(
    item_id: int,
    {model_name.lower()}_data: {model_name}Update,
    repository: {model_name}Repository = Depends(get_{model_name.lower()}_repository)
):
    """Update an existing {model_name}."""
    try:
        {model_name.lower()} = repository.update(item_id, {model_name.lower()}_data)
        if not {model_name.lower()}:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"{model_name} not found"
            )
        return {model_name.lower()}
    except HTTPException:
        raise
    except Exception as e:
        if "unique" in str(e).lower() or "duplicate" in str(e).lower():
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail=f"{model_name} already exists"
            )
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(e)
        )


@router.delete("/{{item_id}}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_{model_name.lower()}(
    item_id: int,
    repository: {model_name}Repository = Depends(get_{model_name.lower()}_repository)
):
    """Delete a {model_name}."""
    try:
        if not repository.delete(item_id):
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"{model_name} not found"
            )
    except HTTPException:
        raise
    except Exception as e:
        if "foreign key" in str(e).lower() or "constraint" in str(e).lower():
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail=f"Cannot delete {model_name}: referenced by other records"
            )
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(e)
        )
'''
    return code


def main():
    parser = argparse.ArgumentParser(
        description="Generate FastAPI CRUD router from SQLModel/Pydantic model"
    )
    parser.add_argument(
        "model",
        help="Model definition as string or path to file containing model"
    )
    parser.add_argument(
        "--pattern",
        choices=["direct", "repository"],
        default="direct",
        help="Architecture pattern (direct DB operations or repository pattern)"
    )
    parser.add_argument(
        "--session",
        choices=["generate", "assume"],
        default="generate",
        help="Session management: generate get_session() or assume get_db() exists"
    )
    parser.add_argument(
        "-o", "--output",
        help="Output file path (default: stdout)"
    )

    args = parser.parse_args()

    # Read model definition
    model_code = args.model
    try:
        with open(model_code, 'r') as f:
            model_code = f.read()
    except FileNotFoundError:
        # Assume it's the model code itself
        pass
    except Exception as e:
        print(f"Error reading file: {e}", file=sys.stderr)
        sys.exit(1)

    # Parse model
    try:
        model_info = parse_model_definition(model_code)
    except ValueError as e:
        print(f"Error parsing model: {e}", file=sys.stderr)
        sys.exit(1)

    # Generate code
    if args.pattern == "direct":
        code = generate_direct_pattern(model_info, args.session)
    else:
        code = generate_repository_pattern(model_info, args.session)

    # Output
    if args.output:
        try:
            with open(args.output, 'w') as f:
                f.write(code)
            print(f"Generated CRUD router written to {args.output}", file=sys.stderr)
        except Exception as e:
            print(f"Error writing output: {e}", file=sys.stderr)
            sys.exit(1)
    else:
        print(code)


if __name__ == "__main__":
    main()
